
services:
    db:
      container_name: country_dictionary_api_app_db
      image: postgres:latest
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: countries_db
      ports:
        - "5432:5432"
